# Generated by Django 4.0.1 on 2022-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
