# Generated by Django 4.0.1 on 2022-03-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_choices_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices_count',
        ),
    ]
